# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 Intel Corporation
# Copyright 2025 Canonical Ltd.

version: 2
updates:

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "America/Los_Angeles"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "America/Los_Angeles"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "America/Los_Angeles"
