# SPDX-FileCopyrightText: 2022 Great Software Laboratory Pvt. Ltd
# SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0


---
info:
  version: 1.0.0
  description: GNBSIM initial local configuration

configuration:
  runConfigProfilesAtStart: true
  singleInterface: false #default value
  execInParallel: false #run all profiles in parallel
  httpServer: # Serves APIs to create/control profiles on the go
    enable: false
    ipAddr: "POD_IP"
    port: 8080
  gnbs: # pool of gNodeBs
    gnb1:
      n2IpAddr: "POD_IP" # gNB N2 interface IP address used to connect to AMF
      n2Port: 9487 # gNB N2 Port used to connect to AMF
      n3IpAddr: 192.168.251.5 # gNB N3 interface IP address used to connect to UPF. when singleInterface mode is false
      #n3IpAddr: "POD_IP" # when gnb is deployed in singleInterface mode
      n3Port: 2152 # gNB N3 Port used to connect to UPF
      name: gnb1 # gNB name that uniquely identify a gNB within application
      globalRanId:
        plmnId:
          mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
          mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
        gNbId:
          bitLength: 24
          gNBValue: 000102 # gNB identifier (3 bytes hex string, range: 000000~FFFFFF)
      supportedTaList:
        - tac: 000001 # Tracking Area Code (3 bytes hex string, range: 000000~FFFFFF)
          broadcastPlmnList:
            - plmnId:
                mcc: 208
                mnc: 93
              taiSliceSupportList:
                - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
                  sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
                - sst: 1
                  sd: 000001
                - sst: 2
      defaultAmf:
        hostName: amf # Host name of AMF
        ipAddr: # AMF IP address
        port: 38412 # AMF port

  customProfiles:
    customProfiles1:
      profileType: custom # profile type
      profileName: custom1 # uniqely identifies a profile within application
      enable: false # Set true to execute the profile, false otherwise.
      execInParallel: false #run all subscribers in parallel
      stepTrigger: true #wait for trigger to move to next step
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 208930100007487
      ueCount: 5
      defaultAs: "192.168.250.1" #default icmp pkt destination
      opc: "981d464c7c52eb6e5036234984ad0bcf"
      key: "5122250214c33e723a5dd523fc145fc0"
      sequenceNumber: "16f3b3f70fc2"
      retransMsg: false
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
        mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      startiteration: iteration1
      iterations:
        #at max 7 actions
        - "name": "iteration1"
          "1": "REGISTRATION-PROCEDURE 5"
          "2": "PDU-SESSION-ESTABLISHMENT-PROCEDURE 5"
          "3": "USER-DATA-PACKET-GENERATION-PROCEDURE 10"
          "next":  "iteration2"
        - "name": "iteration2"
          "1": "AN-RELEASE-PROCEDURE 100"
          "2": "UE-TRIGGERED-SERVICE-REQUEST-PROCEDURE 10"
          "repeat": 5
          "next":  "iteration3"
        - "name": "iteration3"
          "1": "UE-INITIATED-DEREGISTRATION-PROCEDURE 10"
          #"repeat": 0 #default value 0 . i.e execute once
          #"next":  "quit" #default value quit. i.e. no further iteration to run

  profiles: # profile information
    - profileType: register # profile type
      profileName: profile1 # uniqely identifies a profile within application
      enable: false # Set true to execute the profile, false otherwise.
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 208930100007487
      ueCount: 5
      defaultAs: "192.168.250.1" #default icmp pkt destination
      opc: "981d464c7c52eb6e5036234984ad0bcf"
      key: "5122250214c33e723a5dd523fc145fc0"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "internet"
      sNssai:
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      execInParallel: false #run all subscribers within profile in parallel
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
        mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
    - profileType: pdusessest # profile type
      profileName: profile2 # uniqely identifies a profile within application
      enable: false # Set true to execute the profile, false otherwise.
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 208930100007492 # First IMSI. Subsequent values will be used if ueCount is more than 1
      ueCount: 5 # Number of UEs for for which the profile will be executed
      defaultAs: "192.168.250.1" #default icmp pkt destination
      opc: "981d464c7c52eb6e5036234984ad0bcf"
      key: "5122250214c33e723a5dd523fc145fc0"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "internet"
      sNssai:
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      execInParallel: false #run all subscribers within profile in parallel
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>. Should match startImsi
        mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      dataPktCount: 5 # Number of UL user data packets to be transmitted. Common for all UEs
    - profileType: anrelease # profile type
      profileName: profile3 # uniqely identifies a profile within application
      enable: false # Set true to execute the profile, false otherwise.
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 208930100007497 # First IMSI. Subsequent values will be used if ueCount is more than 1
      ueCount: 5 # Number of UEs for for which the profile will be executed
      defaultAs: "192.168.250.1" #default icmp pkt destination
      opc: "981d464c7c52eb6e5036234984ad0bcf"
      key: "5122250214c33e723a5dd523fc145fc0"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "internet"
      sNssai:
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      execInParallel: false #run all subscribers within profile in parallel
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>. Should match startImsi
        mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
    - profileType: uetriggservicereq # profile type
      profileName: profile4 # uniqely identifies a profile within application
      enable: false # Set true to execute the profile, false otherwise.
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 208930100007497 # First IMSI. Subsequent values will be used if ueCount is more than 1
      ueCount: 5 # Number of UEs for for which the profile will be executed
      defaultAs: "192.168.250.1" #default icmp pkt destination
      opc: "981d464c7c52eb6e5036234984ad0bcf"
      key: "5122250214c33e723a5dd523fc145fc0"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "internet"
      retransMsg: false
      sNssai:
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      execInParallel: false #run all subscribers within profile in parallel
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>. Should match startImsi
        mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
    - profileType: deregister # profile type
      profileName: profile5 # uniqely identifies a profile within application
      enable: false # Set true to execute the profile, false otherwise.
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 208930100007497 # First IMSI. Subsequent values will be used if ueCount is more than 1
      ueCount: 5 # Number of UEs for for which the profile will be executed
      defaultAs: "192.168.250.1" #default icmp pkt destination
      opc: "981d464c7c52eb6e5036234984ad0bcf"
      key: "5122250214c33e723a5dd523fc145fc0"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "internet"
      sNssai:
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      execInParallel: false #run all subscribers within profile in parallel
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>. Should match startImsi
        mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
    - profileType: nwtriggeruedereg # profile type
      profileName: profile6 # uniqely identifies a profile within application
      enable: false # Set true to execute the profile, false otherwise.
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 208930100007497 # First IMSI. Subsequent values will be used if ueCount is more than 1
      ueCount: 1 # Number of UEs for for which the profile will be executed
      defaultAs: "192.168.250.1" #default icmp pkt destination
      perUserTimeout: 10 #if no expected event received in this time then treat it as failure
      opc: "981d464c7c52eb6e5036234984ad0bcf"
      key: "5122250214c33e723a5dd523fc145fc0"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "internet"
      sNssai:
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      execInParallel: false #run all subscribers within profile in parallel
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>. Should match startImsi
        mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
    - profileType: uereqpdusessrelease # profile type
      profileName: profile7 # uniqely identifies a profile within application
      enable: false # Set true to execute the profile, false otherwise.
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 208930100007497 # First IMSI. Subsequent values will be used if ueCount is more than 1
      ueCount: 5 # Number of UEs for for which the profile will be executed
      opc: "981d464c7c52eb6e5036234984ad0bcf"
      key: "5122250214c33e723a5dd523fc145fc0"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "internet"
      sNssai:
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      execInParallel: false #run all subscribers within profile in parallel
      defaultAs: "192.168.250.1" #default icmp pkt destination
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>. Should match startImsi
        mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
    - profileType: nwreqpdusessrelease # profile type
      profileName: profile8 # uniqely identifies a profile within application
      enable: false # Set true to execute the profile, false otherwise.
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 208930100007497 # First IMSI. Subsequent values will be used if ueCount is more than 1
      ueCount: 1 # Number of UEs for for which the profile will be executed
      opc: "981d464c7c52eb6e5036234984ad0bcf"
      key: "5122250214c33e723a5dd523fc145fc0"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "internet"
      sNssai:
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      execInParallel: false #run all subscribers within profile in parallel
      defaultAs: "192.168.250.1" #default icmp pkt destination
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>. Should match startImsi
        mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)

logger:
  logLevel: info # how detailed the log will be, values: debug, info, warn, error, fatal, panic
